name: Build and Release

on:
  push:
    branches:
      - master
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Clean directory
        run: ./gradlew clean

      - name: Build with Gradle
        run: ./gradlew build --scan

      - name: Generate Tag Name
        id: tag_name
        run: |
          tag=$(date +"%d/%m/%y-%H/%M")
          echo "TAG_NAME=$tag" >> $GITHUB_ENV

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.TAG_NAME }}',
              sha: context.sha
            })

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/libs/*.jar
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          body: |
            Automated release for ${{ env.TAG_NAME }}

      - name: Get Release Info
        id: release_info
        run: |
          release_data=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.TAG_NAME }}")
          download_url=$(echo "$release_data" | jq -r '.assets[0].browser_download_url')
          echo "DOWNLOAD_URL=$download_url" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s|\[DOWNLOAD\](.*)|\[DOWNLOAD\]($DOWNLOAD_URL)|" README.md
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update DOWNLOAD links in README"
          git push