name: Compile

permissions: write-all

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda

      - name: Build with Gradle
        run: ./gradlew clean && ./gradlew build

      - name: Upload build artifacts
        if: success()
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Plugin
          path: build/libs/*

      - name: Update README.md
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          ARTIFACT_ID: ${{ steps.upload.outputs.artifact-id }}
        run: |
          DOWNLOAD_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ env.ARTIFACT_ID }}"
          sed -i.bak -E "s|\[LATEST BUILD\]\(.*\) \[LATEST DOWNLOAD\]\(.*\)|\[LATEST BUILD\]\($BUILD_URL\) \[LATEST DOWNLOAD\]\($DOWNLOAD_URL\)|" README.md
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update README.md with latest build and download links"
          git push